brew 'coreutils'
brew 'gnu-sed'
brew 'findutils'
brew 'weechat', args: ['with-python@2']
brew 'tmux'
brew 'jq'
brew 'readline'
brew 'the_silver_searcher'
brew 'zsh'
brew 'vim'
brew 'macvim'
brew 'python@2'
